### ISSUE TITLE
Seasons key combos not requiring key Alt

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_seasons#731] opened 2018-01-04 08:30 UTC
Occasionally it is not necessary to use the "Alt" key when accessing for instance the Seasons menu. So only pressing key "S" will access the menu. Or if using developer version, only pressing key "D" will fast forward time. It is fixed by pressing "Alt" once. 

See also #728

**Comment by joskuijpers** [comment] 2018-01-08 17:47
I can't reproduce this. It might be possible to do on Windows because windows uses Alt+Tab. So someone with Windows should try some Alt+Tabbing with different things like GUI, and see if the ALT gets stuck.
If that happens, it is an engine issue.

**Comment by yumi-modding** [comment] 2018-01-08 18:28
Hello,
I can reproduce this issue but I have a very particular setup so I think the issue is more due to giants engine and not the mod itself.
I play on Ubuntu Linux using wine to launch Steam (windows) client and then the game.
I have the feeling that if the game window loses the focus during loading, this situation can happen.
Generally I press Alt and Windows key before starting a game to "unlock" them if engine see them as pressed by error.

**Comment by joskuijpers** [comment] 2018-01-08 18:33
Hmm yes. That could do it. I don't know how the Giants Engine handles input exactly, but it is likely it only received up/down events for keys. So if it misses an UP event, it might think it is kept down?

Did you try pressing the alt key again to see if it unlocks?

**Comment by joskuijpers** [comment] 2018-01-17 14:46
@yumi-modding any update on this?

**Comment by yumi-modding** [comment] 2018-01-17 15:35
@joskuijpers For me the issue is not linked to Seasons but to my particular setup or to Giants Engine itself since I think I had it before using seasons mod (with hudHider for instance).
@reallogger Do you really think there is something to be fixed in seasons? Or maybe you see the issue here since seasons uses Alt key modifier more than other mods. Do you use hudHider that also use this key and would reveal the issue even more easily?

**Comment by joskuijpers** [comment] 2018-01-17 15:38
@yumi-modding @reallogger just copied the report from the forum. We haven't had the issue ourselves.

**Closed** 2018-01-17 16:19 UTC
Labels: analysis, bug
