### ISSUE TITLE
LightAddon mod conflict?

### ISSUE THREAD

**Issue by Spartan086** [RealismusModding/FS17_seasons#199] opened 2017-03-25 18:23 UTC
Hey guys, awesome work you are doing on this mod, really loving it. 

I just updated to the latest version and fairly certain I've spotted a mod conflict. If I am using the LightAddon mod and a vehicle with configured "drl" lights, those lights will always be set to "off". If I turn the seasons mod off the lights regain their functionality. 

Two theories; either light addons reads something changed by your latest "traffic light hack".. but after reading a bit in the light addon script it only seems to... append a function to "self.startMotor"(?).. so maybe its some side effect of the new "won't start of first try if poorly maintained" feature?

Wether this is any concern for you or not; dunno, just giving you a heads up on a possible mod conflict. Feel free to close if you like.

**Comment by joskuijpers** [comment] 2017-03-26 16:01
Hi @Spartan086 
Can you give us a link to both the LightAddon mod and the vehicle? Then we can test.

**Comment by Spartan086** [comment] 2017-03-26 18:31
LightAddon: http://www.farming-simulator.com/mod.php?mod_id=53564
Not the mod I use, but small and will reproduce the problem: https://www.dropbox.com/s/vcriwsgun3mdo81/BMW_i8.zip?dl=1

Start game with only LightAddon and the car active. Start the engine => headlights turn on. (Press F activates additional lights as usual.)
Activate seasons as well and start the engine => no lights turn on. (Press F activates additional lights as usual.)

**Comment by joskuijpers** [comment] 2017-03-26 22:31
Alright, after 3 hours I found the problem.
The problem is the LightAddon. The way they register its spec is convulted, messy and just bad.
I changed their 80 lines with less than 7 and now it works perfectly.

Remove all lines in `addSpecialization:add()`
and replace with:

```lua
    for _, vehicleType in pairs(VehicleTypeUtil.vehicleTypes) do
        if vehicleType ~= nil then
            if SpecializationUtil.hasSpecialization(Lights, vehicleType.specializations) then
                table.insert(vehicleType.specializations, SpecializationUtil.getSpecialization("LightAddon"))
            end
        end
    end
```

You can also replace `return true` in LightAddon.lua::29 with:
```lua
return SpecializationUtil.hasSpecialization(Lights, specializations)
```

**Comment by joskuijpers** [comment] 2017-03-26 22:52
Oops that seems to have broke seasons motorFailure...

**Comment by joskuijpers** [comment] 2017-03-27 11:13
Fixed in latest commit.

**Closed by joskuijpers** 2017-03-27 11:13 UTC

**Comment by Dzi4d3k** [comment] 2017-03-27 12:13
Will it still need fix in LightAddon mod?

**Comment by joskuijpers** [comment] 2017-03-27 12:16
I don't think it does. (Try it ;) )
I emailed VertexDezign suggesting the update to their code.
