### ISSUE TITLE
animal fix

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#547] opened 2017-08-07 18:55 UTC
Please fill in

**Comment by joskuijpers** [comment] 2017-08-07 20:00
(birth) productivity of animals is not based on care of the whole year.

**Comment by joskuijpers** [comment] 2017-08-12 10:19
@baleBaron how are we going to do this?

**Comment by joskuijpers** [comment] 2017-08-12 23:22
Idea is to use a simple running average, but using the number of hours in the gestation period of the animal as `numItems`, instead of the whole length of the average. This is not a true average but it might work.
On top of that, low current-production values can be given more effect.

With 600+ numItems, the effect of an hour low-productivity is <1% so maybe we need some factors here.

**Comment by Timmiej93** [comment] 2017-08-14 17:24
If I may comment on this (my apologies if I'm not meant to), I'd suggest averaging for the entire year, but making the hours in the gestation period have more impact/weight. Only taking the hours in the gestation period into account could create a scenario where your animals barely survive for the entire year, but still reproduce perfectly and fully, just because you took good care of them in the gestation period.

**Comment by reallogger** [comment] 2017-08-14 17:41
@Timmiej93  : Gestation period: Fetal development period from the time of conception until birth

**Comment by joskuijpers** [comment] 2017-08-18 16:34
@reallogger can you give a formular of the running average with the proper variables/constants, and also start value, and a way that treating animals worse has more effect than treating them well?

**Comment by reallogger** [comment] 2017-08-19 00:09
I'll make smth next week. If you want to implement before that make the following:

function updateAnimalProd(oldValue, animalProd)
-- animalProd being the productivity of the animal type at hourChange when this function is called
local seasonLengthFactor = 6 * g_seasons.daysInSeason


return oldValue * (seasonLengthFactor - 1) / seasonLengthFactor + animalProd / seasonLengthFactor

Initial value can be like 50% when you buy the first animal

I'll make smth better when I get in touch with a computer after the weekend :)

**Comment by reallogger** [comment] 2017-08-19 09:06
See also #560 for animal feed quality

**Comment by reallogger** [comment] 2017-08-30 06:20
Almost complete. 

Need to store and load current animal productivity to avoid dip in average productivity when loading savegame and average productivity is updated before game has determined the current productivity.

**Comment by joskuijpers** [comment] 2017-08-31 22:09
If this works it can be merged into develop.

How is it when starting a new savegame or buying a lot of animals? Should we default to 80%: "taken care of by seller"? Also, what happens if you dont have any animals: does it stay at 80% or drop to 0?

**Comment by reallogger** [comment] 2017-08-31 22:49
If you don't have any animals the productivity is 0. New bought animals have productivity 80%. If you have 4 animals and average productivity is 100% and then you buy 4 more, the average productivity of your herd will be 90% after buying.

**Closed by reallogger** 2017-08-31 22:49 UTC
Labels: bug

**Comment by joskuijpers** [comment] 2017-08-31 22:52
great!

**Comment by reallogger** [comment] 2017-08-31 22:56
Also if you start with an existing savegame (i.e. either having an earlier version of Seasons, or starting fresh with Seasons) you will start at 80% average production
